### ISSUE TITLE
A little more detailed set up instructions?

### ISSUE THREAD

**Issue by spitfire** [ntrippar/sekey#13]
I have downloaded the precompiled binary, and followed the "Manual Installation" instructions, then generated, exported and added the public key to my remote host; but the authentication using the generated key doesn't work. Is there anything else I need to do that is not outlined in Readme?

**Comment by ntrippar** [comment]
can you check that the service is running? and also if the SSH_AUTH_SOCK= is set on your env?
for the service look if the process sekey is running in the machine. also to know if the env is right or not can you do the following steps on a terminal "env |grep SSH_AUTH" and give me the result here. 
also you can check doing this
"export SSH_AUTH_SOCK=~/.sekey/ssh-agent.ssh"
and now trying to connect again to the ssh server

**Comment by spitfire** [comment]
Yes, the service is running. I also tried unloading it an running manually as myself:
~ sekey --daemon
Pipe deleted
binding to /Users/mieszko/.sekey/ssh-agent.ssh

I've noted no additional output when trying to connect to ssh after running it.

SSH_AUTH_SOCK is set to /Users/myusername/.sekey/ssh-agent.ssh

**Comment by ntrippar** [comment]
can you run the daemon this way and get the log RUST_LOG=debug ./sekey --daemon that way we will look if the server is sending the identities. or its responding something. you can delete the content of key_blob and pubkey_blob (that are your public keys, but for your privacy)

**Comment by spitfire** [comment]
```RUST_LOG=debug sekey --daemon
Pipe deleted
binding to /Users/mieszko/.sekey/ssh-agent.ssh
DEBUG:ssh_agent::agent: handling new connection
DEBUG:ssh_agent::protocol: reading request
DEBUG:ssh_agent::agent: request: RequestIdentities
DEBUG:ssh_agent::agent: handler: Identities([Identity { key_blob: [0, 0, 0, 19, 101, 99, 100, 115, 97, 45, 115, 104, 97, 50, 45, 110, 105, 115, 116, 112, 50, 53, 54, 0, 0, 0, 8, 110, 105, 115, 116, 112, 50, 53, 54, 0, 0, 0, 65, 4, 131, 160, 141, 141, 215, 136, 122, 220, 103, 1, 6, 156, 244, 232, 251, 13, 138, 15, 131, 33, 11, 1, 101, 135, 96, 129, 211, 132, 203, 14, 0, 164, 41, 98, 71, 61, 10, 254, 164, 143, 167, 94, 187, 43, 51, 96, 171, 108, 150, 109, 109, 27, 17, 254, 104, 192, 66, 180, 85, 92, 109, 140, 253, 47], key_comment: "ecdsa-sha2-nistp256" }])
DEBUG:ssh_agent::protocol: reading request```

**Comment by ntrippar** [comment]
here appears that the server is not recognizing the public key, and is not sending the sign request. maybe your server don't support edcsa? lets try some other stuff, can you add your public key on github (its a really good place to test stuff), and do a ssh -T git@github.com

**Comment by spitfire** [comment]
Yup, that's right - dropper (that's used as ssh server on OpenWRT) does not seem to work with ecdsa key (works with rsa).
I just logged on to another server (FreeNAS) using the key generated with sekey without any issues.

Thanks for the help with troubleshooting this!

Is the usage of ecdsa key with Secure Enclave a hard limit, that cannot be bypassed somehow?

**Comment by ntrippar** [comment]
the Secure Enclave only support ecdsa :( I think that Apple did that way only because they need to sign/encrypt data but they where not thinking on stuff like this. maybe they add more algorithms in the future. Im currently researching more and more to see if I can get more capabilities from this.

**Comment by spitfire** [comment]
Oh, so this is not about the amount of data you can put/read in one "block", but it's specifically supporting one key type.
Anyway - thanks a lot for your help!

**Comment by ntrippar** [comment]
other way could be generate a public-private pair on the enclave, generate a RSA SSH key encrypt it with the enclave and save on the keychain. so every time you want to use the key you have to enable the enclave to decrypt the key. but the key will be in memory on that time. so it can be compromised.

**Comment by spitfire** [comment]
So the private key read from the enclave now is not stored in memory at any point?
That sounds very secure.

**Comment by ntrippar** [comment]
sekey never have access to the private key, and is not stored on memory on any point. the enclave generate they keypair but the private key is only in the secure enclave. when you are logging in to the ssh the server send a sign request matching for the public key, sekey send the signing request to the enclave, you use touchid to enable the enclave to signs the request and return the signature to sekey. so the private is never on the computer and even if you have malware on the computer they can never access the private key

**Comment by spitfire** [comment]
Does this make #2 impossible?

**Comment by ntrippar** [comment]
the #2 is if you are using for example a yubikey is forward the request of identities also to the gpgagent for example and get also the identities from there and return. some people have to use yubikeys because of the companies where they work. so with that they will can use both as same time

**Comment by spitfire** [comment]
So that (GPG support) would actually require additional U2F key to work, and not store it in the Secure Enclave? Would it actually do anything else, than let you confirm (using TouchID sensor) if you want to allow GPG agent to access the GPG key on a U2F device?

**Comment by ntrippar** [comment]
exactly. even you wont need to use TouchID to confirm in that case you will have to confirm in the smarkey(Yubikey), only will work as a proxy sending the requests to the other agent. and the other agent will handle their communication/auth.
