### ISSUE TITLE
How can I tell which key to use for a given host?

### ISSUE THREAD

**Issue by listochkin** [ntrippar/sekey#27]
I have two keys in Sekey vault: `keyA` and `keyB`. I want to use `keyA` for `hostA` and `keyB` for `hostB`. Is there a way to do it in `~/.ssh/config`?

**Comment by ntrippar** [comment]
how the SSH_Agent protocol is implemented. it send all the keys to the host, if you have two diferent keys will work but you will have the issue commented here on the issue #1, im planning to release a new version of sekey (lot of changes, even async) that im working on a fork (locally, i will push in this days), that will add the ability of enable/disable keys.

**Comment by listochkin** [comment]
Still it would be nice to have a configuration in '~/.ssh/config'. It could look like this:

```
Host github.com
  # sekey <keyid>
  ...
```

this way a user wouldn't have to run `sekey` command before and after every remote operation. That would be especially useful when they have to run the same script on a number of machines with each machine using its own key pair for SSH.

**Comment by listochkin** [comment]
Just realized after some digging that [SSH doesn't pass the host name to the agent when it requests the list of identities](http://api.libssh.org/rfc/PROTOCOL.agent), and thus my suggestion wouldn't work without extra commands, like you described in #1

**Comment by ntrippar** [comment]
I checked and works for me, I will update the documentation, I don't want to add code to automatically generate the configuration files, because it can break up with existing configs. and will be a lot of code only for that.

**Comment by listochkin** [comment]
Yep. Tested out and it worked flawlessly! Great job!
