### ISSUE TITLE
Homebrew-Cask

### ISSUE THREAD

**Issue by Manouchehri** [ntrippar/sekey#3]
Looks like it should be possible to use a Cask with the signed release.

https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md

**Comment by ntrippar** [comment]
totally, tonight i will do it.

**Comment by claui** [comment]
@ntrippar [Beat you to it](https://github.com/caskroom/homebrew-cask/pull/41686).

Feel free to update it yourself though whenever you publish new releases!

**Comment by ntrippar** [comment]
Hey, thanks you!. anywaysIi was thinking to package as installer. so automatically set up as a launchagent, (even I think I can do it scripting on the ruby side) then the user only will have to add the enviroment variables.

**Comment by claui** [comment]
> so automatically set up as a launchagent

Good point, especially for non-Homebrew users.

In the meantime, [I have now added the plist to the Cask](https://github.com/caskroom/homebrew-cask/pull/41686/files) as well, and automated as much of the installation as I could. The cask also creates a symlink inside `/usr/local/bin/` now , which points to the binary in the app bundle.

The one thing the user is left to do is to export `SSH_AUTH_SOCK` of course, which is now mentioned at installation time as a `Caveat`.

(Lacking both Sierra and a Touch Bar, I’ve been unable to test whether everything works together though.)

**Comment by ntrippar** [comment]
Awesome work, really thanks you!, i will try it on my laptop and then update the readme with the homebrew-cask instructions :)

**Comment by ntrippar** [comment]
@claui yesterday I worked creating a pkg that automatically install the plist and set the correct user privileges to the folders. I will sign it today and modity your script/branch so we can release on cask :). Really thanks for your help!

**Comment by claui** [comment]
@ntrippar Anything I can do in the meantime to help?

Regardless, feel free to submit a stand-alone release with just the pkg/installer and plist.  
I’ll happily take care of the Cask then.

**Comment by ntrippar** [comment]
@claui Hey i was traveling, tomorrow morning i will upload the pkg. and we can add it directly in the cask!

**Comment by ntrippar** [comment]
@claui I added a pkg installer on the releases! it automatically install the plist. with that we should be fine for the cask

**Comment by ntrippar** [comment]
@claui really didn't find a way to patch your pull request directly on the homebrew-cask repo. here is the code complete if you want to push it there so its clearner the open a new pull request.
I tested this and worked perfectly

https://github.com/ntrippar/homebrew-cask/blob/855c3aba0d800c989db3f0425fdd56357dcad3fb/Casks/sekey.rb

Btw. Muchas Gracias(Thanks you!) for your help!

**Comment by ntrippar** [comment]
I been really late finishing this. but the support for cask is added!

**Comment by willfarrell** [comment]
I wrote a little script that includes it a while back, can finally share it. https://gist.github.com/willfarrell/e9b7553367f5edca0ac7e0b8e9647a04
