### ISSUE TITLE
Solution like ssh-copy-id to upload a key in one step

### ISSUE THREAD

**Issue by rgov** [ntrippar/sekey#38]
The `ssh-copy-id` tool is useful to add your public key to a remote server's `authorized_keys` file. It can be used with SeKey by exporting a public key to a file and then using `ssh-copy-id` with it.

It would be nice if SeKey made this a bit easier, something like

    sekey -u, --upload-key <[USER@]SERVER> <ID>

**Comment by ptescher** [comment]
I just tried this with `SSH_AUTH_SOCK=$HOME/.sekey/ssh-agent.ssh` and just running `ssh-copy-id` and it worked just fine. No file export needed.

**Comment by rgov** [comment]
Indeed that works. Cool!
