### ISSUE TITLE
Change keytype from ecdsa-sha2-nistp256 to ecdsa-sha2-nistp256-sk 

### ISSUE THREAD

**Issue by Firstyear** [ntrippar/sekey#61]
OpenSSH now supports ecdsa-sk and ed25519-sk keys. The '-sk' denotes these are stored on a security key, such as a yubikey.

Since sekey itself is also using hardware backed keys, it could be useful to "indicate" as such an generate these keys as the -sk class so that they can be distinguished from other key types. 

What do you think?

**Comment by martinpaljak** [comment]
Doesn't the -sk indicate "security key" and means a FIDO-type device/key? sekey app and secure enclae is not a fido type device and the protocol and properties of the key are different from fido (sekey being more like a generic PKCS#11 container instead)

**Comment by Firstyear** [comment]
Yeah, that's fair, but I think it's still a good way to indicate "it's hardware backed". Maybe there is a different way to indicate this?

**Comment by martinpaljak** [comment]
"indication" is worthless unless you can verify it. FIDO (in theory) uses attestation. "plain ecc key" like sekey does not (at least not in the context of OpenSSH). A plain p256 key is different from fido p256-sk key, they are just no the same thing.

**Comment by Firstyear** [comment]
Sure, sounds like it's not worth it then.
